version: "3"

services:
  reverse-proxy:
    build:
      context: ./containers/proxy/
      dockerfile: Dockerfile
    container_name: gazamytalk-reverse-proxy
    restart: always
    volumes:
      - ./containers/proxy/webroot:/usr/share/nginx/html
      - ./containers/proxy/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    depends_on:
      - web-server
      - api-server
      - image-server
      - ws-server
    ports:
      - 80:80
      - 443:443

  api-server:
    container_name: gazamytalk-api-server
    build:
      context: ./containers/servers/api-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - LOGIN_DB_HOST=${LOGIN_DB_HOST}
      - LOGIN_DB_PORT=${LOGIN_DB_PORT}
      - LOGIN_DB_USER=${LOGIN_DB_USER}
      - LOGIN_DB_PASSWORD=${LOGIN_DB_PASSWORD}
      - LOGIN_DB_DATABASE=${LOGIN_DB_DATABASE}
      - MAIN_DB_URI=${MAIN_DB_URI}
      - CHAT_DB_URI=${CHAT_DB_URI}
      - SESSION_STORE_URL=${SESSION_STORE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - DEFAULT_USER_IMAGE_PATH="/images/defaultUserImage.png"
      - DEFAULT_ROOM_IMAGE_PATH="/images/defaultRoomImage.png"
      - DEFAULT_USERNAME_MAX_LENGTH=40
    expose:
      - "80"
    depends_on:
      - mysql
      - redis
      - mongodb

  image-server:
    container_name: gazamytalk-image-server
    build:
      context: ./containers/servers/image-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - CURRENT_SERVER_PATH="/images"
      - IMAGES_DIR_PATH="/app/images"
      - SESSION_STORE_URL=${SESSION_STORE_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - SERVER_PORT=80
    volumes:
      - imagedata:/app/images
    depends_on:
      - redis
    expose:
      - 80

  ws-server:
    container_name: gazamytalk-ws-server
    build:
      context: ./containers/servers/ws-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVER_PORT=80
      - CHAT_DB_URI=${CHAT_DB_URI}
    depends_on:
      - mongodb
    expose:
      - 80

  mysql:
    container_name: gazamytalk-mysql
    image: mysql:5.7.21
    restart: always
    volumes:
      - "./containers/databases/mysql/init.d:/docker-entrypoint-initdb.d"
      - "./containers/databases/mysql/data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${LOGIN_DB_ROOT_PASSWORD}
      - MYSQL_USER=${LOGIN_DB_USER}
      - MYSQL_PASSWORD=${LOGIN_DB_PASSWORD}
      - MYSQL_DATABASE=${LOGIN_DB_DATABASE}
    expose:
      - 3306

  redis:
    container_name: gazamytalk-redis
    image: redis:alpine
    restart: always
    expose:
      - 6379

  mongodb:
    container_name: gazamytalk-mongodb
    image: mongo:4.4.18
    restart: always
    volumes:
      - "mongodata:/data/db"
    expose:
      - 27017

  web-server:
    container_name: gazamytalk-web-server
    build:
      context: ./containers/servers/web-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - SESSION_STORE_URL=${SESSION_STORE_URL}
    depends_on:
      - redis
    expose:
      - 80

volumes:
  mongodata:
  imagedata: